name: SureView for LabVIEW
favicon: null
layout_spectrum: 0.4146541168447584
typography_spectrum: 0.8481138553470373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.42416147026233375
  lightness: 0.7031034519895911
  saturation: 0.7637473968788981
  rhythmicContrast: 0.8875086789485067
purpose: []
